// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	admin "api/internal/handler/admin"
	product "api/internal/handler/product"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 获取所有贷款产品列表
					Method:  http.MethodGet,
					Path:    "/products",
					Handler: admin.ListAllLoanProductsHandler(serverCtx),
				},
				{
					// 创建贷款产品
					Method:  http.MethodPost,
					Path:    "/products",
					Handler: admin.CreateLoanProductHandler(serverCtx),
				},
				{
					// 获取贷款产品详情
					Method:  http.MethodGet,
					Path:    "/products/:id",
					Handler: admin.GetLoanProductDetailHandler(serverCtx),
				},
				{
					// 更新贷款产品
					Method:  http.MethodPut,
					Path:    "/products/:id",
					Handler: admin.UpdateLoanProductHandler(serverCtx),
				},
				{
					// 删除贷款产品
					Method:  http.MethodDelete,
					Path:    "/products/:id",
					Handler: admin.DeleteLoanProductHandler(serverCtx),
				},
				{
					// 更新产品状态
					Method:  http.MethodPut,
					Path:    "/products/:id/status",
					Handler: admin.UpdateProductStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin/loanproduct"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取贷款产品列表
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: product.ListLoanProductsHandler(serverCtx),
			},
			{
				// 获取贷款产品详情
				Method:  http.MethodGet,
				Path:    "/products/:id",
				Handler: product.GetLoanProductHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/loanproduct"),
	)
}
