basePath: /
consumes:
- application/json
info:
  title: C端用户服务API
  version: v1.0.0
paths:
  /api/v1/appuser/info:
    get:
      operationId: userGetUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              data: {}
              message:
                type: string
            type: object
      schemes:
      - https
      summary: GetUserInfo
  /api/v1/appuser/profile:
    put:
      consumes:
      - application/json
      operationId: userUpdateUserProfile
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            address:
              type: string
            age:
              type: integer
            gender:
              description: 0:未知 1:男 2:女
              type: integer
            income:
              type: number
            nickname:
              type: string
            occupation:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              data: {}
              message:
                type: string
            type: object
      schemes:
      - https
      summary: UpdateUserProfile
produces:
- application/json
schemes:
- https
swagger: "2.0"
x-date: "2025-06-28 18:59:42"
x-description: This is a goctl generated swagger file.
x-github: https://github.com/zeromicro/go-zero
x-go-zero-doc: https://go-zero.dev/
x-goctl-version: 1.8.4
