// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: loan-rpc.proto

package loan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 贷款申请基础信息
type LoanApplicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 申请ID
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"` // 申请编号
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户ID
	ApplicantName string                 `protobuf:"bytes,4,opt,name=applicant_name,json=applicantName,proto3" json:"applicant_name,omitempty"` // 申请人姓名
	ProductId     int64                  `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`            // 贷款产品ID
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                                        // 申请名称
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                                        // 贷款类型
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`                                  // 申请金额
	Duration      int32                  `protobuf:"varint,9,opt,name=duration,proto3" json:"duration,omitempty"`                               // 贷款期限(月)
	Purpose       string                 `protobuf:"bytes,10,opt,name=purpose,proto3" json:"purpose,omitempty"`                                 // 贷款用途
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态 pending/approved/rejected/cancelled
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`           // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanApplicationInfo) Reset() {
	*x = LoanApplicationInfo{}
	mi := &file_loan_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApplicationInfo) ProtoMessage() {}

func (x *LoanApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApplicationInfo.ProtoReflect.Descriptor instead.
func (*LoanApplicationInfo) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LoanApplicationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanApplicationInfo) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *LoanApplicationInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoanApplicationInfo) GetApplicantName() string {
	if x != nil {
		return x.ApplicantName
	}
	return ""
}

func (x *LoanApplicationInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *LoanApplicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoanApplicationInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoanApplicationInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LoanApplicationInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *LoanApplicationInfo) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *LoanApplicationInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoanApplicationInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LoanApplicationInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 贷款审批记录基础信息
type LoanApprovalInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                     // 审批ID
	ApplicationId    int64                  `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`          // 申请ID
	AuditorId        int64                  `protobuf:"varint,3,opt,name=auditor_id,json=auditorId,proto3" json:"auditor_id,omitempty"`                      // 审核员ID
	AuditorName      string                 `protobuf:"bytes,4,opt,name=auditor_name,json=auditorName,proto3" json:"auditor_name,omitempty"`                 // 审核员姓名
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                              // 审批动作 approve/reject
	Suggestions      string                 `protobuf:"bytes,6,opt,name=suggestions,proto3" json:"suggestions,omitempty"`                                    // 审批意见
	ApprovedAmount   float64                `protobuf:"fixed64,7,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`      // 批准金额
	ApprovedDuration int32                  `protobuf:"varint,8,opt,name=approved_duration,json=approvedDuration,proto3" json:"approved_duration,omitempty"` // 批准期限(月)
	InterestRate     float64                `protobuf:"fixed64,9,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`            // 利率(%)
	CreatedAt        int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                     // 创建时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoanApprovalInfo) Reset() {
	*x = LoanApprovalInfo{}
	mi := &file_loan_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanApprovalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanApprovalInfo) ProtoMessage() {}

func (x *LoanApprovalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanApprovalInfo.ProtoReflect.Descriptor instead.
func (*LoanApprovalInfo) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *LoanApprovalInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanApprovalInfo) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *LoanApprovalInfo) GetAuditorId() int64 {
	if x != nil {
		return x.AuditorId
	}
	return 0
}

func (x *LoanApprovalInfo) GetAuditorName() string {
	if x != nil {
		return x.AuditorName
	}
	return ""
}

func (x *LoanApprovalInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LoanApprovalInfo) GetSuggestions() string {
	if x != nil {
		return x.Suggestions
	}
	return ""
}

func (x *LoanApprovalInfo) GetApprovedAmount() float64 {
	if x != nil {
		return x.ApprovedAmount
	}
	return 0
}

func (x *LoanApprovalInfo) GetApprovedDuration() int32 {
	if x != nil {
		return x.ApprovedDuration
	}
	return 0
}

func (x *LoanApprovalInfo) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *LoanApprovalInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 创建贷款申请
type CreateLoanApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Purpose       string                 `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanApplicationReq) Reset() {
	*x = CreateLoanApplicationReq{}
	mi := &file_loan_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanApplicationReq) ProtoMessage() {}

func (x *CreateLoanApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanApplicationReq.ProtoReflect.Descriptor instead.
func (*CreateLoanApplicationReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLoanApplicationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLoanApplicationReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateLoanApplicationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLoanApplicationReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateLoanApplicationReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateLoanApplicationReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateLoanApplicationReq) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type CreateLoanApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanApplicationResp) Reset() {
	*x = CreateLoanApplicationResp{}
	mi := &file_loan_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanApplicationResp) ProtoMessage() {}

func (x *CreateLoanApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanApplicationResp.ProtoReflect.Descriptor instead.
func (*CreateLoanApplicationResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLoanApplicationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateLoanApplicationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateLoanApplicationResp) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

// 获取贷款申请
type GetLoanApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanApplicationReq) Reset() {
	*x = GetLoanApplicationReq{}
	mi := &file_loan_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanApplicationReq) ProtoMessage() {}

func (x *GetLoanApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanApplicationReq.ProtoReflect.Descriptor instead.
func (*GetLoanApplicationReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetLoanApplicationReq) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type GetLoanApplicationResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ApplicationInfo *LoanApplicationInfo   `protobuf:"bytes,3,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLoanApplicationResp) Reset() {
	*x = GetLoanApplicationResp{}
	mi := &file_loan_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanApplicationResp) ProtoMessage() {}

func (x *GetLoanApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanApplicationResp.ProtoReflect.Descriptor instead.
func (*GetLoanApplicationResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetLoanApplicationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetLoanApplicationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLoanApplicationResp) GetApplicationInfo() *LoanApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

// 获取贷款申请列表
type ListLoanApplicationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanApplicationsReq) Reset() {
	*x = ListLoanApplicationsReq{}
	mi := &file_loan_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanApplicationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanApplicationsReq) ProtoMessage() {}

func (x *ListLoanApplicationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanApplicationsReq.ProtoReflect.Descriptor instead.
func (*ListLoanApplicationsReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListLoanApplicationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLoanApplicationsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListLoanApplicationsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListLoanApplicationsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListLoanApplicationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*LoanApplicationInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanApplicationsResp) Reset() {
	*x = ListLoanApplicationsResp{}
	mi := &file_loan_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanApplicationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanApplicationsResp) ProtoMessage() {}

func (x *ListLoanApplicationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanApplicationsResp.ProtoReflect.Descriptor instead.
func (*ListLoanApplicationsResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListLoanApplicationsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListLoanApplicationsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListLoanApplicationsResp) GetList() []*LoanApplicationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListLoanApplicationsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 更新贷款申请
type UpdateLoanApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Purpose       string                 `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanApplicationReq) Reset() {
	*x = UpdateLoanApplicationReq{}
	mi := &file_loan_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanApplicationReq) ProtoMessage() {}

func (x *UpdateLoanApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanApplicationReq.ProtoReflect.Descriptor instead.
func (*UpdateLoanApplicationReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLoanApplicationReq) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateLoanApplicationReq) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateLoanApplicationReq) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateLoanApplicationReq) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type UpdateLoanApplicationResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ApplicationInfo *LoanApplicationInfo   `protobuf:"bytes,3,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLoanApplicationResp) Reset() {
	*x = UpdateLoanApplicationResp{}
	mi := &file_loan_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanApplicationResp) ProtoMessage() {}

func (x *UpdateLoanApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanApplicationResp.ProtoReflect.Descriptor instead.
func (*UpdateLoanApplicationResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLoanApplicationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateLoanApplicationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateLoanApplicationResp) GetApplicationInfo() *LoanApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

// 撤销贷款申请
type CancelLoanApplicationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLoanApplicationReq) Reset() {
	*x = CancelLoanApplicationReq{}
	mi := &file_loan_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLoanApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLoanApplicationReq) ProtoMessage() {}

func (x *CancelLoanApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLoanApplicationReq.ProtoReflect.Descriptor instead.
func (*CancelLoanApplicationReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *CancelLoanApplicationReq) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *CancelLoanApplicationReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelLoanApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLoanApplicationResp) Reset() {
	*x = CancelLoanApplicationResp{}
	mi := &file_loan_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLoanApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLoanApplicationResp) ProtoMessage() {}

func (x *CancelLoanApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLoanApplicationResp.ProtoReflect.Descriptor instead.
func (*CancelLoanApplicationResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *CancelLoanApplicationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelLoanApplicationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审批贷款申请
type ApproveLoanApplicationReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId    string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AuditorId        int64                  `protobuf:"varint,2,opt,name=auditor_id,json=auditorId,proto3" json:"auditor_id,omitempty"`
	AuditorName      string                 `protobuf:"bytes,3,opt,name=auditor_name,json=auditorName,proto3" json:"auditor_name,omitempty"`
	Action           string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // approve/reject
	Suggestions      string                 `protobuf:"bytes,5,opt,name=suggestions,proto3" json:"suggestions,omitempty"`
	ApprovedAmount   float64                `protobuf:"fixed64,6,opt,name=approved_amount,json=approvedAmount,proto3" json:"approved_amount,omitempty"`
	ApprovedDuration int32                  `protobuf:"varint,7,opt,name=approved_duration,json=approvedDuration,proto3" json:"approved_duration,omitempty"`
	InterestRate     float64                `protobuf:"fixed64,8,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApproveLoanApplicationReq) Reset() {
	*x = ApproveLoanApplicationReq{}
	mi := &file_loan_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveLoanApplicationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveLoanApplicationReq) ProtoMessage() {}

func (x *ApproveLoanApplicationReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveLoanApplicationReq.ProtoReflect.Descriptor instead.
func (*ApproveLoanApplicationReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveLoanApplicationReq) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApproveLoanApplicationReq) GetAuditorId() int64 {
	if x != nil {
		return x.AuditorId
	}
	return 0
}

func (x *ApproveLoanApplicationReq) GetAuditorName() string {
	if x != nil {
		return x.AuditorName
	}
	return ""
}

func (x *ApproveLoanApplicationReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApproveLoanApplicationReq) GetSuggestions() string {
	if x != nil {
		return x.Suggestions
	}
	return ""
}

func (x *ApproveLoanApplicationReq) GetApprovedAmount() float64 {
	if x != nil {
		return x.ApprovedAmount
	}
	return 0
}

func (x *ApproveLoanApplicationReq) GetApprovedDuration() int32 {
	if x != nil {
		return x.ApprovedDuration
	}
	return 0
}

func (x *ApproveLoanApplicationReq) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

type ApproveLoanApplicationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveLoanApplicationResp) Reset() {
	*x = ApproveLoanApplicationResp{}
	mi := &file_loan_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveLoanApplicationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveLoanApplicationResp) ProtoMessage() {}

func (x *ApproveLoanApplicationResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveLoanApplicationResp.ProtoReflect.Descriptor instead.
func (*ApproveLoanApplicationResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveLoanApplicationResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApproveLoanApplicationResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取审批记录列表
type ListLoanApprovalsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanApprovalsReq) Reset() {
	*x = ListLoanApprovalsReq{}
	mi := &file_loan_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanApprovalsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanApprovalsReq) ProtoMessage() {}

func (x *ListLoanApprovalsReq) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanApprovalsReq.ProtoReflect.Descriptor instead.
func (*ListLoanApprovalsReq) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *ListLoanApprovalsReq) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListLoanApprovalsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*LoanApprovalInfo    `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanApprovalsResp) Reset() {
	*x = ListLoanApprovalsResp{}
	mi := &file_loan_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanApprovalsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanApprovalsResp) ProtoMessage() {}

func (x *ListLoanApprovalsResp) ProtoReflect() protoreflect.Message {
	mi := &file_loan_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanApprovalsResp.ProtoReflect.Descriptor instead.
func (*ListLoanApprovalsResp) Descriptor() ([]byte, []int) {
	return file_loan_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *ListLoanApprovalsResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListLoanApprovalsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListLoanApprovalsResp) GetList() []*LoanApprovalInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_loan_rpc_proto protoreflect.FileDescriptor

const file_loan_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0eloan-rpc.proto\x12\x04loan\x1a\x1bgoogle/protobuf/empty.proto\"\xf7\x02\n" +
	"\x13LoanApplicationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12%\n" +
	"\x0eapplicant_name\x18\x04 \x01(\tR\rapplicantName\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x1a\n" +
	"\bduration\x18\t \x01(\x05R\bduration\x12\x18\n" +
	"\apurpose\x18\n" +
	" \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\"\xdf\x02\n" +
	"\x10LoanApprovalInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x03R\rapplicationId\x12\x1d\n" +
	"\n" +
	"auditor_id\x18\x03 \x01(\x03R\tauditorId\x12!\n" +
	"\fauditor_name\x18\x04 \x01(\tR\vauditorName\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12 \n" +
	"\vsuggestions\x18\x06 \x01(\tR\vsuggestions\x12'\n" +
	"\x0fapproved_amount\x18\a \x01(\x01R\x0eapprovedAmount\x12+\n" +
	"\x11approved_duration\x18\b \x01(\x05R\x10approvedDuration\x12#\n" +
	"\rinterest_rate\x18\t \x01(\x01R\finterestRate\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xc8\x01\n" +
	"\x18CreateLoanApplicationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\"p\n" +
	"\x19CreateLoanApplicationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eapplication_id\x18\x03 \x01(\tR\rapplicationId\">\n" +
	"\x15GetLoanApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"\x8c\x01\n" +
	"\x16GetLoanApplicationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x10application_info\x18\x03 \x01(\v2\x19.loan.LoanApplicationInfoR\x0fapplicationInfo\"r\n" +
	"\x17ListLoanApplicationsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x8d\x01\n" +
	"\x18ListLoanApplicationsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04list\x18\x03 \x03(\v2\x19.loan.LoanApplicationInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x8f\x01\n" +
	"\x18UpdateLoanApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\"\x8f\x01\n" +
	"\x19UpdateLoanApplicationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x10application_info\x18\x03 \x01(\v2\x19.loan.LoanApplicationInfoR\x0fapplicationInfo\"Y\n" +
	"\x18CancelLoanApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"I\n" +
	"\x19CancelLoanApplicationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x02\n" +
	"\x19ApproveLoanApplicationReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"auditor_id\x18\x02 \x01(\x03R\tauditorId\x12!\n" +
	"\fauditor_name\x18\x03 \x01(\tR\vauditorName\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12 \n" +
	"\vsuggestions\x18\x05 \x01(\tR\vsuggestions\x12'\n" +
	"\x0fapproved_amount\x18\x06 \x01(\x01R\x0eapprovedAmount\x12+\n" +
	"\x11approved_duration\x18\a \x01(\x05R\x10approvedDuration\x12#\n" +
	"\rinterest_rate\x18\b \x01(\x01R\finterestRate\"J\n" +
	"\x1aApproveLoanApplicationResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x14ListLoanApprovalsReq\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"q\n" +
	"\x15ListLoanApprovalsResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04list\x18\x03 \x03(\v2\x16.loan.LoanApprovalInfoR\x04list2\xe7\x04\n" +
	"\x04Loan\x12X\n" +
	"\x15CreateLoanApplication\x12\x1e.loan.CreateLoanApplicationReq\x1a\x1f.loan.CreateLoanApplicationResp\x12O\n" +
	"\x12GetLoanApplication\x12\x1b.loan.GetLoanApplicationReq\x1a\x1c.loan.GetLoanApplicationResp\x12U\n" +
	"\x14ListLoanApplications\x12\x1d.loan.ListLoanApplicationsReq\x1a\x1e.loan.ListLoanApplicationsResp\x12X\n" +
	"\x15UpdateLoanApplication\x12\x1e.loan.UpdateLoanApplicationReq\x1a\x1f.loan.UpdateLoanApplicationResp\x12X\n" +
	"\x15CancelLoanApplication\x12\x1e.loan.CancelLoanApplicationReq\x1a\x1f.loan.CancelLoanApplicationResp\x12[\n" +
	"\x16ApproveLoanApplication\x12\x1f.loan.ApproveLoanApplicationReq\x1a .loan.ApproveLoanApplicationResp\x12L\n" +
	"\x11ListLoanApprovals\x12\x1a.loan.ListLoanApprovalsReq\x1a\x1b.loan.ListLoanApprovalsRespB\bZ\x06./loanb\x06proto3"

var (
	file_loan_rpc_proto_rawDescOnce sync.Once
	file_loan_rpc_proto_rawDescData []byte
)

func file_loan_rpc_proto_rawDescGZIP() []byte {
	file_loan_rpc_proto_rawDescOnce.Do(func() {
		file_loan_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_rpc_proto_rawDesc), len(file_loan_rpc_proto_rawDesc)))
	})
	return file_loan_rpc_proto_rawDescData
}

var file_loan_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_loan_rpc_proto_goTypes = []any{
	(*LoanApplicationInfo)(nil),        // 0: loan.LoanApplicationInfo
	(*LoanApprovalInfo)(nil),           // 1: loan.LoanApprovalInfo
	(*CreateLoanApplicationReq)(nil),   // 2: loan.CreateLoanApplicationReq
	(*CreateLoanApplicationResp)(nil),  // 3: loan.CreateLoanApplicationResp
	(*GetLoanApplicationReq)(nil),      // 4: loan.GetLoanApplicationReq
	(*GetLoanApplicationResp)(nil),     // 5: loan.GetLoanApplicationResp
	(*ListLoanApplicationsReq)(nil),    // 6: loan.ListLoanApplicationsReq
	(*ListLoanApplicationsResp)(nil),   // 7: loan.ListLoanApplicationsResp
	(*UpdateLoanApplicationReq)(nil),   // 8: loan.UpdateLoanApplicationReq
	(*UpdateLoanApplicationResp)(nil),  // 9: loan.UpdateLoanApplicationResp
	(*CancelLoanApplicationReq)(nil),   // 10: loan.CancelLoanApplicationReq
	(*CancelLoanApplicationResp)(nil),  // 11: loan.CancelLoanApplicationResp
	(*ApproveLoanApplicationReq)(nil),  // 12: loan.ApproveLoanApplicationReq
	(*ApproveLoanApplicationResp)(nil), // 13: loan.ApproveLoanApplicationResp
	(*ListLoanApprovalsReq)(nil),       // 14: loan.ListLoanApprovalsReq
	(*ListLoanApprovalsResp)(nil),      // 15: loan.ListLoanApprovalsResp
}
var file_loan_rpc_proto_depIdxs = []int32{
	0,  // 0: loan.GetLoanApplicationResp.application_info:type_name -> loan.LoanApplicationInfo
	0,  // 1: loan.ListLoanApplicationsResp.list:type_name -> loan.LoanApplicationInfo
	0,  // 2: loan.UpdateLoanApplicationResp.application_info:type_name -> loan.LoanApplicationInfo
	1,  // 3: loan.ListLoanApprovalsResp.list:type_name -> loan.LoanApprovalInfo
	2,  // 4: loan.Loan.CreateLoanApplication:input_type -> loan.CreateLoanApplicationReq
	4,  // 5: loan.Loan.GetLoanApplication:input_type -> loan.GetLoanApplicationReq
	6,  // 6: loan.Loan.ListLoanApplications:input_type -> loan.ListLoanApplicationsReq
	8,  // 7: loan.Loan.UpdateLoanApplication:input_type -> loan.UpdateLoanApplicationReq
	10, // 8: loan.Loan.CancelLoanApplication:input_type -> loan.CancelLoanApplicationReq
	12, // 9: loan.Loan.ApproveLoanApplication:input_type -> loan.ApproveLoanApplicationReq
	14, // 10: loan.Loan.ListLoanApprovals:input_type -> loan.ListLoanApprovalsReq
	3,  // 11: loan.Loan.CreateLoanApplication:output_type -> loan.CreateLoanApplicationResp
	5,  // 12: loan.Loan.GetLoanApplication:output_type -> loan.GetLoanApplicationResp
	7,  // 13: loan.Loan.ListLoanApplications:output_type -> loan.ListLoanApplicationsResp
	9,  // 14: loan.Loan.UpdateLoanApplication:output_type -> loan.UpdateLoanApplicationResp
	11, // 15: loan.Loan.CancelLoanApplication:output_type -> loan.CancelLoanApplicationResp
	13, // 16: loan.Loan.ApproveLoanApplication:output_type -> loan.ApproveLoanApplicationResp
	15, // 17: loan.Loan.ListLoanApprovals:output_type -> loan.ListLoanApprovalsResp
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_loan_rpc_proto_init() }
func file_loan_rpc_proto_init() {
	if File_loan_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_rpc_proto_rawDesc), len(file_loan_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_rpc_proto_goTypes,
		DependencyIndexes: file_loan_rpc_proto_depIdxs,
		MessageInfos:      file_loan_rpc_proto_msgTypes,
	}.Build()
	File_loan_rpc_proto = out.File
	file_loan_rpc_proto_goTypes = nil
	file_loan_rpc_proto_depIdxs = nil
}
