// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	admin "api/internal/handler/admin"
	lease "api/internal/handler/lease"
	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/applications",
					Handler: admin.ListAllLeaseApplicationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/applications/:id",
					Handler: admin.GetLeaseApplicationDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/applications/:id/approvals",
					Handler: admin.ListLeaseApprovalsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/applications/:id/approve",
					Handler: admin.ApproveLeaseApplicationHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin/lease"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/applications",
				Handler: lease.CreateLeaseApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/applications",
				Handler: lease.ListMyLeaseApplicationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/applications/:id",
				Handler: lease.GetMyLeaseApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/applications/:id",
				Handler: lease.UpdateMyLeaseApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/applications/:id/cancel",
				Handler: lease.CancelMyLeaseApplicationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/lease"),
	)
}
