// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: appuser-rpc.proto

package appuser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C端用户基础信息
type AppUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // 手机号
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"` // 0:未知 1:男 2:女
	Occupation    string                 `protobuf:"bytes,7,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Income        float64                `protobuf:"fixed64,9,opt,name=income,proto3" json:"income,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"` // 1:正常 2:冻结 3:禁用
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUserInfo) Reset() {
	*x = AppUserInfo{}
	mi := &file_appuser_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUserInfo) ProtoMessage() {}

func (x *AppUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUserInfo.ProtoReflect.Descriptor instead.
func (*AppUserInfo) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AppUserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppUserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AppUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AppUserInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AppUserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *AppUserInfo) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *AppUserInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AppUserInfo) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *AppUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AppUserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AppUserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 根据账号获取用户
type GetUserByAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByAccountReq) Reset() {
	*x = GetUserByAccountReq{}
	mi := &file_appuser_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByAccountReq) ProtoMessage() {}

func (x *GetUserByAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByAccountReq.ProtoReflect.Descriptor instead.
func (*GetUserByAccountReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByAccountReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 验证用户密码
type VerifyUserPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserPasswordReq) Reset() {
	*x = VerifyUserPasswordReq{}
	mi := &file_appuser_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserPasswordReq) ProtoMessage() {}

func (x *VerifyUserPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyUserPasswordReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyUserPasswordReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *VerifyUserPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 验证密码后的响应
type VerifyUserPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1:正常 2:冻结 3:禁用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserPasswordResp) Reset() {
	*x = VerifyUserPasswordResp{}
	mi := &file_appuser_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserPasswordResp) ProtoMessage() {}

func (x *VerifyUserPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserPasswordResp.ProtoReflect.Descriptor instead.
func (*VerifyUserPasswordResp) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyUserPasswordResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerifyUserPasswordResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 创建用户(注册)
type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_appuser_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 获取用户基础信息
type GetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	mi := &file_appuser_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 更新用户档案
type UpdateUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Occupation    string                 `protobuf:"bytes,5,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Income        float64                `protobuf:"fixed64,7,opt,name=income,proto3" json:"income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_appuser_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserProfileReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserProfileReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateUserProfileReq) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *UpdateUserProfileReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateUserProfileReq) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

// 获取用户列表
type GetUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListReq) Reset() {
	*x = GetUserListReq{}
	mi := &file_appuser_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListReq) ProtoMessage() {}

func (x *GetUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListReq.ProtoReflect.Descriptor instead.
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetUserListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetUserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AppUserInfo         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResp) Reset() {
	*x = GetUserListResp{}
	mi := &file_appuser_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResp) ProtoMessage() {}

func (x *GetUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResp.ProtoReflect.Descriptor instead.
func (*GetUserListResp) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserListResp) GetUsers() []*AppUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetUserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 更新用户状态
type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_appuser_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_appuser_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_appuser_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserStatusReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_appuser_rpc_proto protoreflect.FileDescriptor

const file_appuser_rpc_proto_rawDesc = "" +
	"\n" +
	"\x11appuser-rpc.proto\x12\aappuser\"\xb9\x02\n" +
	"\vAppUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1e\n" +
	"\n" +
	"occupation\x18\a \x01(\tR\n" +
	"occupation\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x16\n" +
	"\x06income\x18\t \x01(\x01R\x06income\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\"/\n" +
	"\x13GetUserByAccountReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"M\n" +
	"\x15VerifyUserPasswordReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"I\n" +
	"\x16VerifyUserPasswordResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"Y\n" +
	"\rCreateUserReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\")\n" +
	"\x0eGetUserInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xc7\x01\n" +
	"\x14UpdateUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x1e\n" +
	"\n" +
	"occupation\x18\x05 \x01(\tR\n" +
	"occupation\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x16\n" +
	"\x06income\x18\a \x01(\x01R\x06income\"j\n" +
	"\x0eGetUserListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"S\n" +
	"\x0fGetUserListResp\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.appuser.AppUserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"^\n" +
	"\x13UpdateUserStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xf6\x03\n" +
	"\aAppUser\x12F\n" +
	"\x10GetUserByAccount\x12\x1c.appuser.GetUserByAccountReq\x1a\x14.appuser.AppUserInfo\x12U\n" +
	"\x12VerifyUserPassword\x12\x1e.appuser.VerifyUserPasswordReq\x1a\x1f.appuser.VerifyUserPasswordResp\x12:\n" +
	"\n" +
	"CreateUser\x12\x16.appuser.CreateUserReq\x1a\x14.appuser.AppUserInfo\x12<\n" +
	"\vGetUserInfo\x12\x17.appuser.GetUserInfoReq\x1a\x14.appuser.AppUserInfo\x12H\n" +
	"\x11UpdateUserProfile\x12\x1d.appuser.UpdateUserProfileReq\x1a\x14.appuser.AppUserInfo\x12@\n" +
	"\vGetUserList\x12\x17.appuser.GetUserListReq\x1a\x18.appuser.GetUserListResp\x12F\n" +
	"\x10UpdateUserStatus\x12\x1c.appuser.UpdateUserStatusReq\x1a\x14.appuser.AppUserInfoB\vZ\t./appuserb\x06proto3"

var (
	file_appuser_rpc_proto_rawDescOnce sync.Once
	file_appuser_rpc_proto_rawDescData []byte
)

func file_appuser_rpc_proto_rawDescGZIP() []byte {
	file_appuser_rpc_proto_rawDescOnce.Do(func() {
		file_appuser_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appuser_rpc_proto_rawDesc), len(file_appuser_rpc_proto_rawDesc)))
	})
	return file_appuser_rpc_proto_rawDescData
}

var file_appuser_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_appuser_rpc_proto_goTypes = []any{
	(*AppUserInfo)(nil),            // 0: appuser.AppUserInfo
	(*GetUserByAccountReq)(nil),    // 1: appuser.GetUserByAccountReq
	(*VerifyUserPasswordReq)(nil),  // 2: appuser.VerifyUserPasswordReq
	(*VerifyUserPasswordResp)(nil), // 3: appuser.VerifyUserPasswordResp
	(*CreateUserReq)(nil),          // 4: appuser.CreateUserReq
	(*GetUserInfoReq)(nil),         // 5: appuser.GetUserInfoReq
	(*UpdateUserProfileReq)(nil),   // 6: appuser.UpdateUserProfileReq
	(*GetUserListReq)(nil),         // 7: appuser.GetUserListReq
	(*GetUserListResp)(nil),        // 8: appuser.GetUserListResp
	(*UpdateUserStatusReq)(nil),    // 9: appuser.UpdateUserStatusReq
}
var file_appuser_rpc_proto_depIdxs = []int32{
	0, // 0: appuser.GetUserListResp.users:type_name -> appuser.AppUserInfo
	1, // 1: appuser.AppUser.GetUserByAccount:input_type -> appuser.GetUserByAccountReq
	2, // 2: appuser.AppUser.VerifyUserPassword:input_type -> appuser.VerifyUserPasswordReq
	4, // 3: appuser.AppUser.CreateUser:input_type -> appuser.CreateUserReq
	5, // 4: appuser.AppUser.GetUserInfo:input_type -> appuser.GetUserInfoReq
	6, // 5: appuser.AppUser.UpdateUserProfile:input_type -> appuser.UpdateUserProfileReq
	7, // 6: appuser.AppUser.GetUserList:input_type -> appuser.GetUserListReq
	9, // 7: appuser.AppUser.UpdateUserStatus:input_type -> appuser.UpdateUserStatusReq
	0, // 8: appuser.AppUser.GetUserByAccount:output_type -> appuser.AppUserInfo
	3, // 9: appuser.AppUser.VerifyUserPassword:output_type -> appuser.VerifyUserPasswordResp
	0, // 10: appuser.AppUser.CreateUser:output_type -> appuser.AppUserInfo
	0, // 11: appuser.AppUser.GetUserInfo:output_type -> appuser.AppUserInfo
	0, // 12: appuser.AppUser.UpdateUserProfile:output_type -> appuser.AppUserInfo
	8, // 13: appuser.AppUser.GetUserList:output_type -> appuser.GetUserListResp
	0, // 14: appuser.AppUser.UpdateUserStatus:output_type -> appuser.AppUserInfo
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_appuser_rpc_proto_init() }
func file_appuser_rpc_proto_init() {
	if File_appuser_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appuser_rpc_proto_rawDesc), len(file_appuser_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appuser_rpc_proto_goTypes,
		DependencyIndexes: file_appuser_rpc_proto_depIdxs,
		MessageInfos:      file_appuser_rpc_proto_msgTypes,
	}.Build()
	File_appuser_rpc_proto = out.File
	file_appuser_rpc_proto_goTypes = nil
	file_appuser_rpc_proto_depIdxs = nil
}
