// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ChangePasswordReq struct {
	Phone       string `json:"phone"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResp struct {
}

type DeleteUserReq struct {
	Phone string `json:"phone"`
}

type DeleteUserResp struct {
}

type GetUserInfoReq struct {
	Phone string `json:"phone"`
}

type GetUserInfoResp struct {
	UserInfo UserInfo `json:"user_info"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"` // 返回纯JWT token，Postman可配置为Bearer Token自动添加前缀
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type RegisterResp struct {
	Token string `json:"token"` // 返回纯JWT token，Postman可配置为Bearer Token自动添加前缀
}

type UpdateUserInfoReq struct {
	UserInfo UserInfo `json:"user_info"`
}

type UpdateUserInfoResp struct {
	UserInfo UserInfo `json:"user_info"`
}

type UpdateUserStatusReq struct {
	Phone  string `json:"phone"`
	Status int    `json:"status"`
}

type UpdateUserStatusResp struct {
	Status int `json:"status"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Nickname  string `json:"nickname"`
	Age       int    `json:"age"`
	Gender    int    `json:"gender"`
	Role      string `json:"role"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
