// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ChangePasswordReq struct {
	Phone       string `json:"phone"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type ChangePasswordResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type DeleteUserReq struct {
	Phone string `json:"phone"`
}

type DeleteUserResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type GetUserInfoReq struct {
	Phone string `json:"phone"`
}

type GetUserInfoResp struct {
	Code     int32    `json:"code"`
	Message  string   `json:"message"`
	UserInfo UserInfo `json:"user_info"`
}

type LoginReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

type LogoutReq struct {
	Token string `json:"token"`
}

type LogoutResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

type RegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type RegisterResp struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
	Token   string `json:"token"`
}

type UpdateUserInfoReq struct {
	UserInfo UserInfo `json:"user_info"`
}

type UpdateUserInfoResp struct {
	Code     int32    `json:"code"`
	Message  string   `json:"message"`
	UserInfo UserInfo `json:"user_info"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Phone     string `json:"phone"`
	Name      string `json:"name"`
	Nickname  string `json:"nickname"`
	Age       int    `json:"age"`
	Gender    int    `json:"gender"`
	Role      string `json:"role"`
	Status    int    `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}
