// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type CreateUserReq struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Name     string   `json:"name"`
	Email    string   `json:"email,optional"`
	Mobile   string   `json:"mobile,optional"`
	Roles    []string `json:"roles"`
}

type DataResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type GetUserListReq struct {
	Page    int    `form:"page,default=1"`
	Size    int    `form:"size,default=10"`
	Keyword string `form:"keyword,optional"`
	Status  int    `form:"status,optional"`
}

type PageResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type UpdateUserReq struct {
	UserID int64    `path:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email,optional"`
	Mobile string   `json:"mobile,optional"`
	Status int      `json:"status"`
	Roles  []string `json:"roles"`
}
