basePath: /
consumes:
- application/json
info:
  title: C端用户服务API
  version: v1.0.0
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      operationId: authLogin
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            password:
              type: string
            phone:
              type: string
          required:
          - phone
          - password
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
              token:
                type: string
            type: object
      schemes:
      - https
      summary: Login
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      operationId: authJwtLogout
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            token:
              type: string
          required:
          - token
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
            type: object
      schemes:
      - https
      summary: Logout
  /api/v1/auth/password:
    post:
      consumes:
      - application/json
      operationId: authJwtChangePassword
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            new_password:
              type: string
            old_password:
              type: string
            phone:
              type: string
          required:
          - phone
          - old_password
          - new_password
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
            type: object
      schemes:
      - https
      summary: ChangePassword
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      operationId: authRegister
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            password:
              type: string
            phone:
              type: string
          required:
          - phone
          - password
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
              token:
                type: string
            type: object
      schemes:
      - https
      summary: Register
  /api/v1/user/delete:
    post:
      consumes:
      - application/json
      operationId: infoDeleteUser
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            phone:
              type: string
          required:
          - phone
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
            type: object
      schemes:
      - https
      summary: DeleteUser
  /api/v1/user/info:
    get:
      operationId: infoGetUserByPhone
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            phone:
              type: string
          required:
          - phone
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
              user_info:
                properties:
                  address:
                    type: string
                  age:
                    type: integer
                  created_at:
                    type: integer
                  gender:
                    type: integer
                  id:
                    type: integer
                  income:
                    type: number
                  name:
                    type: string
                  nickname:
                    type: string
                  occupation:
                    type: string
                  phone:
                    type: string
                  status:
                    type: integer
                  updated_at:
                    type: integer
                required:
                - id
                - phone
                - name
                - nickname
                - age
                - gender
                - occupation
                - address
                - income
                - status
                - created_at
                - updated_at
                type: object
            type: object
      schemes:
      - https
      summary: GetUserByPhone
    put:
      consumes:
      - application/json
      operationId: infoUpdateUserInfo
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            user_info:
              properties:
                address:
                  type: string
                age:
                  type: integer
                created_at:
                  type: integer
                gender:
                  type: integer
                id:
                  type: integer
                income:
                  type: number
                name:
                  type: string
                nickname:
                  type: string
                occupation:
                  type: string
                phone:
                  type: string
                status:
                  type: integer
                updated_at:
                  type: integer
              required:
              - id
              - phone
              - name
              - nickname
              - age
              - gender
              - occupation
              - address
              - income
              - status
              - created_at
              - updated_at
              type: object
          required:
          - user_info
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: ""
          schema:
            properties:
              code:
                type: integer
              message:
                type: string
              user_info:
                properties:
                  address:
                    type: string
                  age:
                    type: integer
                  created_at:
                    type: integer
                  gender:
                    type: integer
                  id:
                    type: integer
                  income:
                    type: number
                  name:
                    type: string
                  nickname:
                    type: string
                  occupation:
                    type: string
                  phone:
                    type: string
                  status:
                    type: integer
                  updated_at:
                    type: integer
                required:
                - id
                - phone
                - name
                - nickname
                - age
                - gender
                - occupation
                - address
                - income
                - status
                - created_at
                - updated_at
                type: object
            type: object
      schemes:
      - https
      summary: UpdateUserInfo
produces:
- application/json
schemes:
- https
swagger: "2.0"
x-date: "2025-06-30 04:11:18"
x-description: This is a goctl generated swagger file.
x-github: https://github.com/zeromicro/go-zero
x-go-zero-doc: https://go-zero.dev/
x-goctl-version: 1.8.4
