// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: oauser-rpc.proto

package oauser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 后台用户信息
type OAUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 1:正常 2:禁用
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Roles         []string               `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"` // 用户拥有的角色列表(简化为字符串数组)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAUserInfo) Reset() {
	*x = OAUserInfo{}
	mi := &file_oauser_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAUserInfo) ProtoMessage() {}

func (x *OAUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAUserInfo.ProtoReflect.Descriptor instead.
func (*OAUserInfo) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *OAUserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OAUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OAUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OAUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OAUserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *OAUserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OAUserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OAUserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetOAUserByUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAUserByUsernameReq) Reset() {
	*x = GetOAUserByUsernameReq{}
	mi := &file_oauser_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAUserByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAUserByUsernameReq) ProtoMessage() {}

func (x *GetOAUserByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAUserByUsernameReq.ProtoReflect.Descriptor instead.
func (*GetOAUserByUsernameReq) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetOAUserByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type VerifyOAPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOAPasswordReq) Reset() {
	*x = VerifyOAPasswordReq{}
	mi := &file_oauser_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOAPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOAPasswordReq) ProtoMessage() {}

func (x *VerifyOAPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOAPasswordReq.ProtoReflect.Descriptor instead.
func (*VerifyOAPasswordReq) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyOAPasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyOAPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyOAPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *OAUserInfo            `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOAPasswordResp) Reset() {
	*x = VerifyOAPasswordResp{}
	mi := &file_oauser_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOAPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOAPasswordResp) ProtoMessage() {}

func (x *VerifyOAPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOAPasswordResp.ProtoReflect.Descriptor instead.
func (*VerifyOAPasswordResp) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOAPasswordResp) GetUserInfo() *OAUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetOAUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"` // 按用户名或姓名搜索
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`  // 按状态筛选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAUserListReq) Reset() {
	*x = GetOAUserListReq{}
	mi := &file_oauser_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAUserListReq) ProtoMessage() {}

func (x *GetOAUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAUserListReq.ProtoReflect.Descriptor instead.
func (*GetOAUserListReq) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetOAUserListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOAUserListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetOAUserListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetOAUserListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetOAUserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*OAUserInfo          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAUserListResp) Reset() {
	*x = GetOAUserListResp{}
	mi := &file_oauser_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAUserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAUserListResp) ProtoMessage() {}

func (x *GetOAUserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAUserListResp.ProtoReflect.Descriptor instead.
func (*GetOAUserListResp) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetOAUserListResp) GetUsers() []*OAUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetOAUserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOAUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"` // 简化为字符串数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOAUserReq) Reset() {
	*x = CreateOAUserReq{}
	mi := &file_oauser_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOAUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOAUserReq) ProtoMessage() {}

func (x *CreateOAUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOAUserReq.ProtoReflect.Descriptor instead.
func (*CreateOAUserReq) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOAUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateOAUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateOAUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOAUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOAUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateOAUserReq) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateOAUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOAUserReq) Reset() {
	*x = UpdateOAUserReq{}
	mi := &file_oauser_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOAUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOAUserReq) ProtoMessage() {}

func (x *UpdateOAUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauser_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOAUserReq.ProtoReflect.Descriptor instead.
func (*UpdateOAUserReq) Descriptor() ([]byte, []int) {
	return file_oauser_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOAUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOAUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOAUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateOAUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateOAUserReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateOAUserReq) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_oauser_rpc_proto protoreflect.FileDescriptor

const file_oauser_rpc_proto_rawDesc = "" +
	"\n" +
	"\x10oauser-rpc.proto\x12\x06oauser\"\xc7\x01\n" +
	"\n" +
	"OAUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x14\n" +
	"\x05roles\x18\b \x03(\tR\x05roles\"4\n" +
	"\x16GetOAUserByUsernameReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"M\n" +
	"\x13VerifyOAPasswordReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\x14VerifyOAPasswordResp\x12.\n" +
	"\buserInfo\x18\x01 \x01(\v2\x12.oauser.OAUserInfoR\buserInfo\"l\n" +
	"\x10GetOAUserListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"S\n" +
	"\x11GetOAUserListResp\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.oauser.OAUserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa1\x01\n" +
	"\x0fCreateOAUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\"\x9a\x01\n" +
	"\x0fUpdateOAUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles2\xed\x03\n" +
	"\x06OAUser\x12I\n" +
	"\x13GetOAUserByUsername\x12\x1e.oauser.GetOAUserByUsernameReq\x1a\x12.oauser.OAUserInfo\x12M\n" +
	"\x10VerifyOAPassword\x12\x1b.oauser.VerifyOAPasswordReq\x1a\x1c.oauser.VerifyOAPasswordResp\x12D\n" +
	"\rGetOAUserList\x12\x18.oauser.GetOAUserListReq\x1a\x19.oauser.GetOAUserListResp\x12E\n" +
	"\x0fGetOAUserDetail\x12\x1e.oauser.GetOAUserByUsernameReq\x1a\x12.oauser.OAUserInfo\x12;\n" +
	"\fCreateOAUser\x12\x17.oauser.CreateOAUserReq\x1a\x12.oauser.OAUserInfo\x12;\n" +
	"\fUpdateOAUser\x12\x17.oauser.UpdateOAUserReq\x1a\x12.oauser.OAUserInfo\x12B\n" +
	"\fDeleteOAUser\x12\x1e.oauser.GetOAUserByUsernameReq\x1a\x12.oauser.OAUserInfoB\n" +
	"Z\b./oauserb\x06proto3"

var (
	file_oauser_rpc_proto_rawDescOnce sync.Once
	file_oauser_rpc_proto_rawDescData []byte
)

func file_oauser_rpc_proto_rawDescGZIP() []byte {
	file_oauser_rpc_proto_rawDescOnce.Do(func() {
		file_oauser_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauser_rpc_proto_rawDesc), len(file_oauser_rpc_proto_rawDesc)))
	})
	return file_oauser_rpc_proto_rawDescData
}

var file_oauser_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oauser_rpc_proto_goTypes = []any{
	(*OAUserInfo)(nil),             // 0: oauser.OAUserInfo
	(*GetOAUserByUsernameReq)(nil), // 1: oauser.GetOAUserByUsernameReq
	(*VerifyOAPasswordReq)(nil),    // 2: oauser.VerifyOAPasswordReq
	(*VerifyOAPasswordResp)(nil),   // 3: oauser.VerifyOAPasswordResp
	(*GetOAUserListReq)(nil),       // 4: oauser.GetOAUserListReq
	(*GetOAUserListResp)(nil),      // 5: oauser.GetOAUserListResp
	(*CreateOAUserReq)(nil),        // 6: oauser.CreateOAUserReq
	(*UpdateOAUserReq)(nil),        // 7: oauser.UpdateOAUserReq
}
var file_oauser_rpc_proto_depIdxs = []int32{
	0, // 0: oauser.VerifyOAPasswordResp.userInfo:type_name -> oauser.OAUserInfo
	0, // 1: oauser.GetOAUserListResp.users:type_name -> oauser.OAUserInfo
	1, // 2: oauser.OAUser.GetOAUserByUsername:input_type -> oauser.GetOAUserByUsernameReq
	2, // 3: oauser.OAUser.VerifyOAPassword:input_type -> oauser.VerifyOAPasswordReq
	4, // 4: oauser.OAUser.GetOAUserList:input_type -> oauser.GetOAUserListReq
	1, // 5: oauser.OAUser.GetOAUserDetail:input_type -> oauser.GetOAUserByUsernameReq
	6, // 6: oauser.OAUser.CreateOAUser:input_type -> oauser.CreateOAUserReq
	7, // 7: oauser.OAUser.UpdateOAUser:input_type -> oauser.UpdateOAUserReq
	1, // 8: oauser.OAUser.DeleteOAUser:input_type -> oauser.GetOAUserByUsernameReq
	0, // 9: oauser.OAUser.GetOAUserByUsername:output_type -> oauser.OAUserInfo
	3, // 10: oauser.OAUser.VerifyOAPassword:output_type -> oauser.VerifyOAPasswordResp
	5, // 11: oauser.OAUser.GetOAUserList:output_type -> oauser.GetOAUserListResp
	0, // 12: oauser.OAUser.GetOAUserDetail:output_type -> oauser.OAUserInfo
	0, // 13: oauser.OAUser.CreateOAUser:output_type -> oauser.OAUserInfo
	0, // 14: oauser.OAUser.UpdateOAUser:output_type -> oauser.OAUserInfo
	0, // 15: oauser.OAUser.DeleteOAUser:output_type -> oauser.OAUserInfo
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_oauser_rpc_proto_init() }
func file_oauser_rpc_proto_init() {
	if File_oauser_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauser_rpc_proto_rawDesc), len(file_oauser_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauser_rpc_proto_goTypes,
		DependencyIndexes: file_oauser_rpc_proto_depIdxs,
		MessageInfos:      file_oauser_rpc_proto_msgTypes,
	}.Build()
	File_oauser_rpc_proto = out.File
	file_oauser_rpc_proto_goTypes = nil
	file_oauser_rpc_proto_depIdxs = nil
}
