// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CreateLoanProductReq struct {
	ProductCode  string  `json:"product_code"`
	Name         string  `json:"name"`
	Type         string  `json:"type"`
	MaxAmount    float64 `json:"max_amount"`
	MinAmount    float64 `json:"min_amount"`
	MaxDuration  int32   `json:"max_duration"`
	MinDuration  int32   `json:"min_duration"`
	InterestRate float64 `json:"interest_rate"`
	Description  string  `json:"description"`
}

type CreateLoanProductResp struct {
	Code    int32           `json:"code"`    // 添加标准响应格式
	Message string          `json:"message"` // 添加标准响应格式
	Data    LoanProductInfo `json:"data"`    // 添加数据字段
}

type DeleteLoanProductReq struct {
	Id string `path:"id"`
}

type DeleteLoanProductResp struct {
	Code    int32  `json:"code"`    // 添加标准响应格式
	Message string `json:"message"` // 添加标准响应格式
}

type GetLoanProductDetailReq struct {
	Id string `path:"id"`
}

type GetLoanProductReq struct {
	Id string `path:"id"`
}

type GetLoanProductResp struct {
	Code    int32           `json:"code"`    // 添加标准响应格式
	Message string          `json:"message"` // 添加标准响应格式
	Data    LoanProductInfo `json:"data"`    // 添加数据字段
}

type ListLoanProductsReq struct {
	Page    int32  `form:"page,default=1"`  // 修改为int32统一分页参数
	Size    int32  `form:"size,default=10"` // 修改为int32统一分页参数
	Type    string `form:"type,optional"`
	Status  int32  `form:"status,optional"`
	Keyword string `form:"keyword,optional"`
}

type ListLoanProductsResp struct {
	Code    int32             `json:"code"`    // 添加标准响应格式
	Message string            `json:"message"` // 添加标准响应格式
	List    []LoanProductInfo `json:"list"`
	Total   int64             `json:"total"`
}

type LoanProductInfo struct {
	Id           int64   `json:"id"`
	ProductCode  string  `json:"product_code"`
	Name         string  `json:"name"`
	Type         string  `json:"type"`
	MaxAmount    float64 `json:"max_amount"`
	MinAmount    float64 `json:"min_amount"`
	MaxDuration  int32   `json:"max_duration"`
	MinDuration  int32   `json:"min_duration"`
	InterestRate float64 `json:"interest_rate"`
	Description  string  `json:"description"`
	Status       int32   `json:"status"`
	CreatedAt    int64   `json:"created_at"`
	UpdatedAt    int64   `json:"updated_at"`
}

type UpdateLoanProductReq struct {
	Id           string  `path:"id"` // 修改为string类型
	Name         string  `json:"name"`
	Type         string  `json:"type"`
	MaxAmount    float64 `json:"max_amount"`
	MinAmount    float64 `json:"min_amount"`
	MaxDuration  int32   `json:"max_duration"`
	MinDuration  int32   `json:"min_duration"`
	InterestRate float64 `json:"interest_rate"`
	Description  string  `json:"description"`
	Status       int32   `json:"status"`
}

type UpdateLoanProductResp struct {
	Code    int32           `json:"code"`    // 添加标准响应格式
	Message string          `json:"message"` // 添加标准响应格式
	Data    LoanProductInfo `json:"data"`    // 添加数据字段
}

type UpdateProductStatusReq struct {
	Id     string `path:"id"` // 修改为string类型
	Status int32  `json:"status"`
}

type UpdateProductStatusResp struct {
	Code    int32  `json:"code"`    // 添加标准响应格式
	Message string `json:"message"` // 添加标准响应格式
}
