// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type CommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DataResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type PageResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type UpdateProfileReq struct {
	Nickname   string  `json:"nickname,optional"`
	Age        int     `json:"age,optional"`
	Gender     int     `json:"gender,optional"` // 0:未知 1:男 2:女
	Occupation string  `json:"occupation,optional"`
	Address    string  `json:"address,optional"`
	Income     float64 `json:"income,optional"`
}
