// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth-rpc.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C端用户登录请求
type AppLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 手机号
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppLoginReq) Reset() {
	*x = AppLoginReq{}
	mi := &file_auth_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppLoginReq) ProtoMessage() {}

func (x *AppLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppLoginReq.ProtoReflect.Descriptor instead.
func (*AppLoginReq) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AppLoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AppLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// B端用户登录请求
type OALoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OALoginReq) Reset() {
	*x = OALoginReq{}
	mi := &file_auth_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OALoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OALoginReq) ProtoMessage() {}

func (x *OALoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OALoginReq.ProtoReflect.Descriptor instead.
func (*OALoginReq) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *OALoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OALoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire  int64                  `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshExpire int64                  `protobuf:"varint,4,opt,name=refreshExpire,proto3" json:"refreshExpire,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	UserType      string                 `protobuf:"bytes,6,opt,name=userType,proto3" json:"userType,omitempty"` // "app" or "oa"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_auth_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetRefreshExpire() int64 {
	if x != nil {
		return x.RefreshExpire
	}
	return 0
}

func (x *LoginResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResp) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

// 生成Token请求
type GenerateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserType      string                 `protobuf:"bytes,2,opt,name=userType,proto3" json:"userType,omitempty"` // "app" or "oa"
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenReq) Reset() {
	*x = GenerateTokenReq{}
	mi := &file_auth_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenReq) ProtoMessage() {}

func (x *GenerateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenReq.ProtoReflect.Descriptor instead.
func (*GenerateTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateTokenReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateTokenReq) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *GenerateTokenReq) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 生成Token响应
type GenerateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	AccessExpire  int64                  `protobuf:"varint,2,opt,name=accessExpire,proto3" json:"accessExpire,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	RefreshExpire int64                  `protobuf:"varint,4,opt,name=refreshExpire,proto3" json:"refreshExpire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResp) Reset() {
	*x = GenerateTokenResp{}
	mi := &file_auth_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResp) ProtoMessage() {}

func (x *GenerateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResp.ProtoReflect.Descriptor instead.
func (*GenerateTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GenerateTokenResp) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

func (x *GenerateTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GenerateTokenResp) GetRefreshExpire() int64 {
	if x != nil {
		return x.RefreshExpire
	}
	return 0
}

// 校验Token请求
type ValidateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenReq) Reset() {
	*x = ValidateTokenReq{}
	mi := &file_auth_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenReq) ProtoMessage() {}

func (x *ValidateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenReq.ProtoReflect.Descriptor instead.
func (*ValidateTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 校验Token响应
type ValidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserType      string                 `protobuf:"bytes,2,opt,name=userType,proto3" json:"userType,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	IsValid       bool                   `protobuf:"varint,4,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResp) Reset() {
	*x = ValidateTokenResp{}
	mi := &file_auth_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResp) ProtoMessage() {}

func (x *ValidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResp.ProtoReflect.Descriptor instead.
func (*ValidateTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateTokenResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResp) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *ValidateTokenResp) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateTokenResp) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

// 使Token失效响应
type InvalidateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateTokenResp) Reset() {
	*x = InvalidateTokenResp{}
	mi := &file_auth_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateTokenResp) ProtoMessage() {}

func (x *InvalidateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateTokenResp.ProtoReflect.Descriptor instead.
func (*InvalidateTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *InvalidateTokenResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_rpc_proto protoreflect.FileDescriptor

const file_auth_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0eauth-rpc.proto\x12\x04auth\"C\n" +
	"\vAppLoginReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"D\n" +
	"\n" +
	"OALoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xcf\x01\n" +
	"\tLoginResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\faccessExpire\x18\x02 \x01(\x03R\faccessExpire\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12$\n" +
	"\rrefreshExpire\x18\x04 \x01(\x03R\rrefreshExpire\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserType\x18\x06 \x01(\tR\buserType\"\\\n" +
	"\x10GenerateTokenReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserType\x18\x02 \x01(\tR\buserType\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"\xa3\x01\n" +
	"\x11GenerateTokenResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\faccessExpire\x18\x02 \x01(\x03R\faccessExpire\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12$\n" +
	"\rrefreshExpire\x18\x04 \x01(\x03R\rrefreshExpire\"4\n" +
	"\x10ValidateTokenReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"w\n" +
	"\x11ValidateTokenResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserType\x18\x02 \x01(\tR\buserType\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x18\n" +
	"\aisValid\x18\x04 \x01(\bR\aisValid\"/\n" +
	"\x13InvalidateTokenResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xae\x02\n" +
	"\x04Auth\x12.\n" +
	"\bAppLogin\x12\x11.auth.AppLoginReq\x1a\x0f.auth.LoginResp\x12,\n" +
	"\aOALogin\x12\x10.auth.OALoginReq\x1a\x0f.auth.LoginResp\x12@\n" +
	"\rGenerateToken\x12\x16.auth.GenerateTokenReq\x1a\x17.auth.GenerateTokenResp\x12@\n" +
	"\rValidateToken\x12\x16.auth.ValidateTokenReq\x1a\x17.auth.ValidateTokenResp\x12D\n" +
	"\x0fInvalidateToken\x12\x16.auth.ValidateTokenReq\x1a\x19.auth.InvalidateTokenRespB\bZ\x06./authb\x06proto3"

var (
	file_auth_rpc_proto_rawDescOnce sync.Once
	file_auth_rpc_proto_rawDescData []byte
)

func file_auth_rpc_proto_rawDescGZIP() []byte {
	file_auth_rpc_proto_rawDescOnce.Do(func() {
		file_auth_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_rpc_proto_rawDesc), len(file_auth_rpc_proto_rawDesc)))
	})
	return file_auth_rpc_proto_rawDescData
}

var file_auth_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_rpc_proto_goTypes = []any{
	(*AppLoginReq)(nil),         // 0: auth.AppLoginReq
	(*OALoginReq)(nil),          // 1: auth.OALoginReq
	(*LoginResp)(nil),           // 2: auth.LoginResp
	(*GenerateTokenReq)(nil),    // 3: auth.GenerateTokenReq
	(*GenerateTokenResp)(nil),   // 4: auth.GenerateTokenResp
	(*ValidateTokenReq)(nil),    // 5: auth.ValidateTokenReq
	(*ValidateTokenResp)(nil),   // 6: auth.ValidateTokenResp
	(*InvalidateTokenResp)(nil), // 7: auth.InvalidateTokenResp
}
var file_auth_rpc_proto_depIdxs = []int32{
	0, // 0: auth.Auth.AppLogin:input_type -> auth.AppLoginReq
	1, // 1: auth.Auth.OALogin:input_type -> auth.OALoginReq
	3, // 2: auth.Auth.GenerateToken:input_type -> auth.GenerateTokenReq
	5, // 3: auth.Auth.ValidateToken:input_type -> auth.ValidateTokenReq
	5, // 4: auth.Auth.InvalidateToken:input_type -> auth.ValidateTokenReq
	2, // 5: auth.Auth.AppLogin:output_type -> auth.LoginResp
	2, // 6: auth.Auth.OALogin:output_type -> auth.LoginResp
	4, // 7: auth.Auth.GenerateToken:output_type -> auth.GenerateTokenResp
	6, // 8: auth.Auth.ValidateToken:output_type -> auth.ValidateTokenResp
	7, // 9: auth.Auth.InvalidateToken:output_type -> auth.InvalidateTokenResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_rpc_proto_init() }
func file_auth_rpc_proto_init() {
	if File_auth_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_rpc_proto_rawDesc), len(file_auth_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_rpc_proto_goTypes,
		DependencyIndexes: file_auth_rpc_proto_depIdxs,
		MessageInfos:      file_auth_rpc_proto_msgTypes,
	}.Build()
	File_auth_rpc_proto = out.File
	file_auth_rpc_proto_goTypes = nil
	file_auth_rpc_proto_depIdxs = nil
}
