// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: loanproduct-rpc.proto

package loanproduct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 贷款产品信息
type LoanProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductCode   string                 `protobuf:"bytes,2,opt,name=productCode,proto3" json:"productCode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,5,opt,name=maxAmount,proto3" json:"maxAmount,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,6,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	MaxDuration   int32                  `protobuf:"varint,7,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`    // 最大期限(月)
	MinDuration   int32                  `protobuf:"varint,8,opt,name=minDuration,proto3" json:"minDuration,omitempty"`    // 最小期限(月)
	InterestRate  float64                `protobuf:"fixed64,9,opt,name=interestRate,proto3" json:"interestRate,omitempty"` // 年利率(%)
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"` // 1:上架 2:下架
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanProductInfo) Reset() {
	*x = LoanProductInfo{}
	mi := &file_loanproduct_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanProductInfo) ProtoMessage() {}

func (x *LoanProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanProductInfo.ProtoReflect.Descriptor instead.
func (*LoanProductInfo) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LoanProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoanProductInfo) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *LoanProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoanProductInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoanProductInfo) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *LoanProductInfo) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *LoanProductInfo) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *LoanProductInfo) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *LoanProductInfo) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *LoanProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoanProductInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LoanProductInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LoanProductInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 添加删除操作响应
type DeleteLoanProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoanProductResp) Reset() {
	*x = DeleteLoanProductResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoanProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoanProductResp) ProtoMessage() {}

func (x *DeleteLoanProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoanProductResp.ProtoReflect.Descriptor instead.
func (*DeleteLoanProductResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{1}
}

// 添加状态更新响应
type UpdateProductStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStatusResp) Reset() {
	*x = UpdateProductStatusResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStatusResp) ProtoMessage() {}

func (x *UpdateProductStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateProductStatusResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{2}
}

// 标准响应格式
type GetLoanProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoanProductInfo       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanProductResp) Reset() {
	*x = GetLoanProductResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanProductResp) ProtoMessage() {}

func (x *GetLoanProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanProductResp.ProtoReflect.Descriptor instead.
func (*GetLoanProductResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetLoanProductResp) GetData() *LoanProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateLoanProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoanProductInfo       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanProductResp) Reset() {
	*x = CreateLoanProductResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanProductResp) ProtoMessage() {}

func (x *CreateLoanProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanProductResp.ProtoReflect.Descriptor instead.
func (*CreateLoanProductResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLoanProductResp) GetData() *LoanProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLoanProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoanProductInfo       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanProductResp) Reset() {
	*x = UpdateLoanProductResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanProductResp) ProtoMessage() {}

func (x *UpdateLoanProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanProductResp.ProtoReflect.Descriptor instead.
func (*UpdateLoanProductResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLoanProductResp) GetData() *LoanProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取贷款产品 - 支持通过ID或产品编码查询
type GetLoanProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 产品ID (可选)
	ProductCode   string                 `protobuf:"bytes,2,opt,name=productCode,proto3" json:"productCode,omitempty"` // 产品编码 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanProductReq) Reset() {
	*x = GetLoanProductReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanProductReq) ProtoMessage() {}

func (x *GetLoanProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanProductReq.ProtoReflect.Descriptor instead.
func (*GetLoanProductReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetLoanProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLoanProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

// 获取贷款产品列表
type ListLoanProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanProductsReq) Reset() {
	*x = ListLoanProductsReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanProductsReq) ProtoMessage() {}

func (x *ListLoanProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanProductsReq.ProtoReflect.Descriptor instead.
func (*ListLoanProductsReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListLoanProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLoanProductsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListLoanProductsReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListLoanProductsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListLoanProductsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListLoanProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LoanProductInfo     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 产品列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanProductsResp) Reset() {
	*x = ListLoanProductsResp{}
	mi := &file_loanproduct_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanProductsResp) ProtoMessage() {}

func (x *ListLoanProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanProductsResp.ProtoReflect.Descriptor instead.
func (*ListLoanProductsResp) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *ListLoanProductsResp) GetList() []*LoanProductInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListLoanProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 创建贷款产品
type CreateLoanProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,4,opt,name=maxAmount,proto3" json:"maxAmount,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,5,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	MaxDuration   int32                  `protobuf:"varint,6,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`
	MinDuration   int32                  `protobuf:"varint,7,opt,name=minDuration,proto3" json:"minDuration,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,8,opt,name=interestRate,proto3" json:"interestRate,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanProductReq) Reset() {
	*x = CreateLoanProductReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanProductReq) ProtoMessage() {}

func (x *CreateLoanProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanProductReq.ProtoReflect.Descriptor instead.
func (*CreateLoanProductReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLoanProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CreateLoanProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLoanProductReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateLoanProductReq) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *CreateLoanProductReq) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CreateLoanProductReq) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *CreateLoanProductReq) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *CreateLoanProductReq) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *CreateLoanProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 更新贷款产品
type UpdateLoanProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	MaxAmount     float64                `protobuf:"fixed64,4,opt,name=maxAmount,proto3" json:"maxAmount,omitempty"`
	MinAmount     float64                `protobuf:"fixed64,5,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	MaxDuration   int32                  `protobuf:"varint,6,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`
	MinDuration   int32                  `protobuf:"varint,7,opt,name=minDuration,proto3" json:"minDuration,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,8,opt,name=interestRate,proto3" json:"interestRate,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanProductReq) Reset() {
	*x = UpdateLoanProductReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanProductReq) ProtoMessage() {}

func (x *UpdateLoanProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanProductReq.ProtoReflect.Descriptor instead.
func (*UpdateLoanProductReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateLoanProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLoanProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLoanProductReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateLoanProductReq) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *UpdateLoanProductReq) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *UpdateLoanProductReq) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *UpdateLoanProductReq) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *UpdateLoanProductReq) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *UpdateLoanProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 删除贷款产品
type DeleteLoanProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoanProductReq) Reset() {
	*x = DeleteLoanProductReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoanProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoanProductReq) ProtoMessage() {}

func (x *DeleteLoanProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoanProductReq.ProtoReflect.Descriptor instead.
func (*DeleteLoanProductReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteLoanProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 更新产品状态
type UpdateProductStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStatusReq) Reset() {
	*x = UpdateProductStatusReq{}
	mi := &file_loanproduct_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStatusReq) ProtoMessage() {}

func (x *UpdateProductStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_loanproduct_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateProductStatusReq) Descriptor() ([]byte, []int) {
	return file_loanproduct_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_loanproduct_rpc_proto protoreflect.FileDescriptor

const file_loanproduct_rpc_proto_rawDesc = "" +
	"\n" +
	"\x15loanproduct-rpc.proto\x12\vloanproduct\"\x85\x03\n" +
	"\x0fLoanProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vproductCode\x18\x02 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tmaxAmount\x18\x05 \x01(\x01R\tmaxAmount\x12\x1c\n" +
	"\tminAmount\x18\x06 \x01(\x01R\tminAmount\x12 \n" +
	"\vmaxDuration\x18\a \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\b \x01(\x05R\vminDuration\x12\"\n" +
	"\finterestRate\x18\t \x01(\x01R\finterestRate\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\f \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\r \x01(\x03R\tupdatedAt\"\x17\n" +
	"\x15DeleteLoanProductResp\"\x19\n" +
	"\x17UpdateProductStatusResp\"F\n" +
	"\x12GetLoanProductResp\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.loanproduct.LoanProductInfoR\x04data\"I\n" +
	"\x15CreateLoanProductResp\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.loanproduct.LoanProductInfoR\x04data\"I\n" +
	"\x15UpdateLoanProductResp\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.loanproduct.LoanProductInfoR\x04data\"E\n" +
	"\x11GetLoanProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vproductCode\x18\x02 \x01(\tR\vproductCode\"\x83\x01\n" +
	"\x13ListLoanProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"^\n" +
	"\x14ListLoanProductsResp\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.loanproduct.LoanProductInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa6\x02\n" +
	"\x14CreateLoanProductReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tmaxAmount\x18\x04 \x01(\x01R\tmaxAmount\x12\x1c\n" +
	"\tminAmount\x18\x05 \x01(\x01R\tminAmount\x12 \n" +
	"\vmaxDuration\x18\x06 \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\a \x01(\x05R\vminDuration\x12\"\n" +
	"\finterestRate\x18\b \x01(\x01R\finterestRate\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"\x94\x02\n" +
	"\x14UpdateLoanProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tmaxAmount\x18\x04 \x01(\x01R\tmaxAmount\x12\x1c\n" +
	"\tminAmount\x18\x05 \x01(\x01R\tminAmount\x12 \n" +
	"\vmaxDuration\x18\x06 \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\a \x01(\x05R\vminDuration\x12\"\n" +
	"\finterestRate\x18\b \x01(\x01R\finterestRate\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"&\n" +
	"\x14DeleteLoanProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x16UpdateProductStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status2\xb6\x04\n" +
	"\x12LoanProductService\x12Q\n" +
	"\x0eGetLoanProduct\x12\x1e.loanproduct.GetLoanProductReq\x1a\x1f.loanproduct.GetLoanProductResp\x12W\n" +
	"\x10ListLoanProducts\x12 .loanproduct.ListLoanProductsReq\x1a!.loanproduct.ListLoanProductsResp\x12Z\n" +
	"\x11CreateLoanProduct\x12!.loanproduct.CreateLoanProductReq\x1a\".loanproduct.CreateLoanProductResp\x12Z\n" +
	"\x11UpdateLoanProduct\x12!.loanproduct.UpdateLoanProductReq\x1a\".loanproduct.UpdateLoanProductResp\x12Z\n" +
	"\x11DeleteLoanProduct\x12!.loanproduct.DeleteLoanProductReq\x1a\".loanproduct.DeleteLoanProductResp\x12`\n" +
	"\x13UpdateProductStatus\x12#.loanproduct.UpdateProductStatusReq\x1a$.loanproduct.UpdateProductStatusRespB\x0fZ\r./loanproductb\x06proto3"

var (
	file_loanproduct_rpc_proto_rawDescOnce sync.Once
	file_loanproduct_rpc_proto_rawDescData []byte
)

func file_loanproduct_rpc_proto_rawDescGZIP() []byte {
	file_loanproduct_rpc_proto_rawDescOnce.Do(func() {
		file_loanproduct_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loanproduct_rpc_proto_rawDesc), len(file_loanproduct_rpc_proto_rawDesc)))
	})
	return file_loanproduct_rpc_proto_rawDescData
}

var file_loanproduct_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_loanproduct_rpc_proto_goTypes = []any{
	(*LoanProductInfo)(nil),         // 0: loanproduct.LoanProductInfo
	(*DeleteLoanProductResp)(nil),   // 1: loanproduct.DeleteLoanProductResp
	(*UpdateProductStatusResp)(nil), // 2: loanproduct.UpdateProductStatusResp
	(*GetLoanProductResp)(nil),      // 3: loanproduct.GetLoanProductResp
	(*CreateLoanProductResp)(nil),   // 4: loanproduct.CreateLoanProductResp
	(*UpdateLoanProductResp)(nil),   // 5: loanproduct.UpdateLoanProductResp
	(*GetLoanProductReq)(nil),       // 6: loanproduct.GetLoanProductReq
	(*ListLoanProductsReq)(nil),     // 7: loanproduct.ListLoanProductsReq
	(*ListLoanProductsResp)(nil),    // 8: loanproduct.ListLoanProductsResp
	(*CreateLoanProductReq)(nil),    // 9: loanproduct.CreateLoanProductReq
	(*UpdateLoanProductReq)(nil),    // 10: loanproduct.UpdateLoanProductReq
	(*DeleteLoanProductReq)(nil),    // 11: loanproduct.DeleteLoanProductReq
	(*UpdateProductStatusReq)(nil),  // 12: loanproduct.UpdateProductStatusReq
}
var file_loanproduct_rpc_proto_depIdxs = []int32{
	0,  // 0: loanproduct.GetLoanProductResp.data:type_name -> loanproduct.LoanProductInfo
	0,  // 1: loanproduct.CreateLoanProductResp.data:type_name -> loanproduct.LoanProductInfo
	0,  // 2: loanproduct.UpdateLoanProductResp.data:type_name -> loanproduct.LoanProductInfo
	0,  // 3: loanproduct.ListLoanProductsResp.list:type_name -> loanproduct.LoanProductInfo
	6,  // 4: loanproduct.LoanProductService.GetLoanProduct:input_type -> loanproduct.GetLoanProductReq
	7,  // 5: loanproduct.LoanProductService.ListLoanProducts:input_type -> loanproduct.ListLoanProductsReq
	9,  // 6: loanproduct.LoanProductService.CreateLoanProduct:input_type -> loanproduct.CreateLoanProductReq
	10, // 7: loanproduct.LoanProductService.UpdateLoanProduct:input_type -> loanproduct.UpdateLoanProductReq
	11, // 8: loanproduct.LoanProductService.DeleteLoanProduct:input_type -> loanproduct.DeleteLoanProductReq
	12, // 9: loanproduct.LoanProductService.UpdateProductStatus:input_type -> loanproduct.UpdateProductStatusReq
	3,  // 10: loanproduct.LoanProductService.GetLoanProduct:output_type -> loanproduct.GetLoanProductResp
	8,  // 11: loanproduct.LoanProductService.ListLoanProducts:output_type -> loanproduct.ListLoanProductsResp
	4,  // 12: loanproduct.LoanProductService.CreateLoanProduct:output_type -> loanproduct.CreateLoanProductResp
	5,  // 13: loanproduct.LoanProductService.UpdateLoanProduct:output_type -> loanproduct.UpdateLoanProductResp
	1,  // 14: loanproduct.LoanProductService.DeleteLoanProduct:output_type -> loanproduct.DeleteLoanProductResp
	2,  // 15: loanproduct.LoanProductService.UpdateProductStatus:output_type -> loanproduct.UpdateProductStatusResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_loanproduct_rpc_proto_init() }
func file_loanproduct_rpc_proto_init() {
	if File_loanproduct_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loanproduct_rpc_proto_rawDesc), len(file_loanproduct_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loanproduct_rpc_proto_goTypes,
		DependencyIndexes: file_loanproduct_rpc_proto_depIdxs,
		MessageInfos:      file_loanproduct_rpc_proto_msgTypes,
	}.Build()
	File_loanproduct_rpc_proto = out.File
	file_loanproduct_rpc_proto_goTypes = nil
	file_loanproduct_rpc_proto_depIdxs = nil
}
