// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type AppLoginReq struct {
	Account  string `json:"account"` // 手机号
	Password string `json:"password"`
}

type CommonResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DataResp struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type OALoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}
