// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ApproveLoanApplicationReq struct {
	ApplicationId    string  `path:"id"`
	Action           string  `json:"action"`
	Suggestions      string  `json:"suggestions"`
	ApprovedAmount   float64 `json:"approved_amount"`
	ApprovedDuration int32   `json:"approved_duration"`
	InterestRate     float64 `json:"interest_rate"`
}

type ApproveLoanApplicationResp struct {
}

type CancelLoanApplicationReq struct {
	ApplicationId string `path:"id"`
	Reason        string `json:"reason"`
}

type CancelLoanApplicationResp struct {
}

type CreateLoanApplicationReq struct {
	ProductId int64   `json:"product_id"`
	Name      string  `json:"name"`
	Type      string  `json:"type"`
	Amount    float64 `json:"amount"`
	Duration  int32   `json:"duration"`
	Purpose   string  `json:"purpose"`
}

type CreateLoanApplicationResp struct {
	ApplicationId string `json:"application_id"`
}

type GetLoanApplicationReq struct {
	ApplicationId string `json:"application_id"`
}

type GetLoanApplicationResp struct {
	ApplicationInfo LoanApplicationInfo `json:"application_info"`
}

type ListLoanApplicationsReq struct {
	Page   int32  `form:"page,default=1"`  // 修改为int32统一分页参数
	Size   int32  `form:"size,default=10"` // 修改为int32统一分页参数
	UserId int64  `form:"user_id,optional"`
	Status string `form:"status,optional"`
}

type ListLoanApplicationsResp struct {
	List  []LoanApplicationInfo `json:"list"`
	Total int64                 `json:"total"`
}

type ListLoanApprovalsReq struct {
	ApplicationId string `form:"application_id"`
}

type ListLoanApprovalsResp struct {
	List []LoanApprovalInfo `json:"list"`
}

type LoanApplicationInfo struct {
	Id            int64   `json:"id"`
	ApplicationId string  `json:"application_id"`
	UserId        int64   `json:"user_id"`
	ApplicantName string  `json:"applicant_name"`
	ProductId     int64   `json:"product_id"`
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	Amount        float64 `json:"amount"`
	Duration      int32   `json:"duration"`
	Purpose       string  `json:"purpose"`
	Status        string  `json:"status"`
	CreatedAt     int64   `json:"created_at"`
	UpdatedAt     int64   `json:"updated_at"`
}

type LoanApprovalInfo struct {
	Id               int64   `json:"id"`
	ApplicationId    int64   `json:"application_id"`
	AuditorId        int64   `json:"auditor_id"`
	AuditorName      string  `json:"auditor_name"`
	Action           string  `json:"action"`
	Suggestions      string  `json:"suggestions"`
	ApprovedAmount   float64 `json:"approved_amount"`
	ApprovedDuration int32   `json:"approved_duration"`
	InterestRate     float64 `json:"interest_rate"`
	CreatedAt        int64   `json:"created_at"`
}

type UpdateLoanApplicationReq struct {
	ApplicationId string  `path:"id"`
	Amount        float64 `json:"amount"`
	Duration      int32   `json:"duration"`
	Purpose       string  `json:"purpose"`
}

type UpdateLoanApplicationResp struct {
	ApplicationInfo LoanApplicationInfo `json:"application_info"`
}
