// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: leaseproduct-rpc.proto

package leaseproduct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 租赁产品信息
type LeaseProductInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // 产品ID
	ProductCode    string                 `protobuf:"bytes,2,opt,name=productCode,proto3" json:"productCode,omitempty"`         // 产品编码
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                       // 产品名称
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                       // 租赁类型
	Machinery      string                 `protobuf:"bytes,5,opt,name=machinery,proto3" json:"machinery,omitempty"`             // 设备名称
	Brand          string                 `protobuf:"bytes,6,opt,name=brand,proto3" json:"brand,omitempty"`                     // 品牌
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`                     // 型号
	DailyRate      float64                `protobuf:"fixed64,8,opt,name=dailyRate,proto3" json:"dailyRate,omitempty"`           // 日租金
	Deposit        float64                `protobuf:"fixed64,9,opt,name=deposit,proto3" json:"deposit,omitempty"`               // 押金
	MaxDuration    int32                  `protobuf:"varint,10,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`       // 最大租期(天)
	MinDuration    int32                  `protobuf:"varint,11,opt,name=minDuration,proto3" json:"minDuration,omitempty"`       // 最小租期(天)
	Description    string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`        // 产品描述
	InventoryCount int32                  `protobuf:"varint,13,opt,name=inventoryCount,proto3" json:"inventoryCount,omitempty"` // 库存数量
	AvailableCount int32                  `protobuf:"varint,14,opt,name=availableCount,proto3" json:"availableCount,omitempty"` // 可用数量
	Status         int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`                 // 状态 1:上架 2:下架
	CreatedAt      int64                  `protobuf:"varint,16,opt,name=createdAt,proto3" json:"createdAt,omitempty"`           // 创建时间
	UpdatedAt      int64                  `protobuf:"varint,17,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`           // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseProductInfo) Reset() {
	*x = LeaseProductInfo{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseProductInfo) ProtoMessage() {}

func (x *LeaseProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseProductInfo.ProtoReflect.Descriptor instead.
func (*LeaseProductInfo) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseProductInfo) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *LeaseProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaseProductInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeaseProductInfo) GetMachinery() string {
	if x != nil {
		return x.Machinery
	}
	return ""
}

func (x *LeaseProductInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *LeaseProductInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LeaseProductInfo) GetDailyRate() float64 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *LeaseProductInfo) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *LeaseProductInfo) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *LeaseProductInfo) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *LeaseProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LeaseProductInfo) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

func (x *LeaseProductInfo) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *LeaseProductInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LeaseProductInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *LeaseProductInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 添加删除操作响应
type DeleteLeaseProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeaseProductResp) Reset() {
	*x = DeleteLeaseProductResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeaseProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeaseProductResp) ProtoMessage() {}

func (x *DeleteLeaseProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeaseProductResp.ProtoReflect.Descriptor instead.
func (*DeleteLeaseProductResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{1}
}

// 标准响应格式
type GetLeaseProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LeaseProductInfo      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseProductResp) Reset() {
	*x = GetLeaseProductResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseProductResp) ProtoMessage() {}

func (x *GetLeaseProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseProductResp.ProtoReflect.Descriptor instead.
func (*GetLeaseProductResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeaseProductResp) GetData() *LeaseProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateLeaseProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LeaseProductInfo      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseProductResp) Reset() {
	*x = CreateLeaseProductResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseProductResp) ProtoMessage() {}

func (x *CreateLeaseProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseProductResp.ProtoReflect.Descriptor instead.
func (*CreateLeaseProductResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLeaseProductResp) GetData() *LeaseProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLeaseProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LeaseProductInfo      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaseProductResp) Reset() {
	*x = UpdateLeaseProductResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaseProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaseProductResp) ProtoMessage() {}

func (x *UpdateLeaseProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaseProductResp.ProtoReflect.Descriptor instead.
func (*UpdateLeaseProductResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLeaseProductResp) GetData() *LeaseProductInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取租赁产品请求
type GetLeaseProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"` // 产品编码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseProductReq) Reset() {
	*x = GetLeaseProductReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseProductReq) ProtoMessage() {}

func (x *GetLeaseProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseProductReq.ProtoReflect.Descriptor instead.
func (*GetLeaseProductReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaseProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

// 获取租赁产品列表请求
type ListLeaseProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`      // 页码
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`      // 每页数量
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`       // 产品类型
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`     // 品牌
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`  // 状态
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"` // 关键词
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaseProductsReq) Reset() {
	*x = ListLeaseProductsReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaseProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaseProductsReq) ProtoMessage() {}

func (x *ListLeaseProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaseProductsReq.ProtoReflect.Descriptor instead.
func (*ListLeaseProductsReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListLeaseProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLeaseProductsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListLeaseProductsReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListLeaseProductsReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListLeaseProductsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListLeaseProductsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListLeaseProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*LeaseProductInfo    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 产品列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaseProductsResp) Reset() {
	*x = ListLeaseProductsResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaseProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaseProductsResp) ProtoMessage() {}

func (x *ListLeaseProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaseProductsResp.ProtoReflect.Descriptor instead.
func (*ListLeaseProductsResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListLeaseProductsResp) GetList() []*LeaseProductInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListLeaseProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 创建租赁产品请求
type CreateLeaseProductReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductCode    string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"`         // 产品编码
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 产品名称
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                       // 产品类型
	Machinery      string                 `protobuf:"bytes,4,opt,name=machinery,proto3" json:"machinery,omitempty"`             // 设备名称
	Brand          string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`                     // 品牌
	Model          string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`                     // 型号
	DailyRate      float64                `protobuf:"fixed64,7,opt,name=dailyRate,proto3" json:"dailyRate,omitempty"`           // 日租金
	Deposit        float64                `protobuf:"fixed64,8,opt,name=deposit,proto3" json:"deposit,omitempty"`               // 押金
	MaxDuration    int32                  `protobuf:"varint,9,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`        // 最大租期(天)
	MinDuration    int32                  `protobuf:"varint,10,opt,name=minDuration,proto3" json:"minDuration,omitempty"`       // 最小租期(天)
	Description    string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`        // 产品描述
	InventoryCount int32                  `protobuf:"varint,12,opt,name=inventoryCount,proto3" json:"inventoryCount,omitempty"` // 库存数量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLeaseProductReq) Reset() {
	*x = CreateLeaseProductReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseProductReq) ProtoMessage() {}

func (x *CreateLeaseProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseProductReq.ProtoReflect.Descriptor instead.
func (*CreateLeaseProductReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLeaseProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CreateLeaseProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLeaseProductReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateLeaseProductReq) GetMachinery() string {
	if x != nil {
		return x.Machinery
	}
	return ""
}

func (x *CreateLeaseProductReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateLeaseProductReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateLeaseProductReq) GetDailyRate() float64 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *CreateLeaseProductReq) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *CreateLeaseProductReq) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *CreateLeaseProductReq) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *CreateLeaseProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLeaseProductReq) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

// 更新租赁产品请求
type UpdateLeaseProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"`   // 产品编码
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                 // 产品名称
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                 // 产品类型
	Machinery     string                 `protobuf:"bytes,4,opt,name=machinery,proto3" json:"machinery,omitempty"`       // 设备名称
	Brand         string                 `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`               // 品牌
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`               // 型号
	DailyRate     float64                `protobuf:"fixed64,7,opt,name=dailyRate,proto3" json:"dailyRate,omitempty"`     // 日租金
	Deposit       float64                `protobuf:"fixed64,8,opt,name=deposit,proto3" json:"deposit,omitempty"`         // 押金
	MaxDuration   int32                  `protobuf:"varint,9,opt,name=maxDuration,proto3" json:"maxDuration,omitempty"`  // 最大租期(天)
	MinDuration   int32                  `protobuf:"varint,10,opt,name=minDuration,proto3" json:"minDuration,omitempty"` // 最小租期(天)
	Description   string                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`  // 产品描述
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`           // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaseProductReq) Reset() {
	*x = UpdateLeaseProductReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaseProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaseProductReq) ProtoMessage() {}

func (x *UpdateLeaseProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaseProductReq.ProtoReflect.Descriptor instead.
func (*UpdateLeaseProductReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLeaseProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetMachinery() string {
	if x != nil {
		return x.Machinery
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetDailyRate() float64 {
	if x != nil {
		return x.DailyRate
	}
	return 0
}

func (x *UpdateLeaseProductReq) GetDeposit() float64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *UpdateLeaseProductReq) GetMaxDuration() int32 {
	if x != nil {
		return x.MaxDuration
	}
	return 0
}

func (x *UpdateLeaseProductReq) GetMinDuration() int32 {
	if x != nil {
		return x.MinDuration
	}
	return 0
}

func (x *UpdateLeaseProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLeaseProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 删除租赁产品请求
type DeleteLeaseProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"` // 产品编码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeaseProductReq) Reset() {
	*x = DeleteLeaseProductReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeaseProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeaseProductReq) ProtoMessage() {}

func (x *DeleteLeaseProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeaseProductReq.ProtoReflect.Descriptor instead.
func (*DeleteLeaseProductReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLeaseProductReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

// 库存检查请求
type CheckInventoryAvailabilityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=productCode,proto3" json:"productCode,omitempty"` // 产品编码
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`      // 数量
	StartDate     string                 `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`     // 开始日期
	EndDate       string                 `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`         // 结束日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInventoryAvailabilityReq) Reset() {
	*x = CheckInventoryAvailabilityReq{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInventoryAvailabilityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInventoryAvailabilityReq) ProtoMessage() {}

func (x *CheckInventoryAvailabilityReq) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInventoryAvailabilityReq.ProtoReflect.Descriptor instead.
func (*CheckInventoryAvailabilityReq) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *CheckInventoryAvailabilityReq) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *CheckInventoryAvailabilityReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckInventoryAvailabilityReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CheckInventoryAvailabilityReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CheckInventoryAvailabilityResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`           // 是否可用
	AvailableCount int32                  `protobuf:"varint,2,opt,name=availableCount,proto3" json:"availableCount,omitempty"` // 可用数量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckInventoryAvailabilityResp) Reset() {
	*x = CheckInventoryAvailabilityResp{}
	mi := &file_leaseproduct_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInventoryAvailabilityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInventoryAvailabilityResp) ProtoMessage() {}

func (x *CheckInventoryAvailabilityResp) ProtoReflect() protoreflect.Message {
	mi := &file_leaseproduct_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInventoryAvailabilityResp.ProtoReflect.Descriptor instead.
func (*CheckInventoryAvailabilityResp) Descriptor() ([]byte, []int) {
	return file_leaseproduct_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *CheckInventoryAvailabilityResp) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckInventoryAvailabilityResp) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

var File_leaseproduct_rpc_proto protoreflect.FileDescriptor

const file_leaseproduct_rpc_proto_rawDesc = "" +
	"\n" +
	"\x16leaseproduct-rpc.proto\x12\fleaseproduct\"\xf8\x03\n" +
	"\x10LeaseProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vproductCode\x18\x02 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1c\n" +
	"\tmachinery\x18\x05 \x01(\tR\tmachinery\x12\x14\n" +
	"\x05brand\x18\x06 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x1c\n" +
	"\tdailyRate\x18\b \x01(\x01R\tdailyRate\x12\x18\n" +
	"\adeposit\x18\t \x01(\x01R\adeposit\x12 \n" +
	"\vmaxDuration\x18\n" +
	" \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\v \x01(\x05R\vminDuration\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12&\n" +
	"\x0einventoryCount\x18\r \x01(\x05R\x0einventoryCount\x12&\n" +
	"\x0eavailableCount\x18\x0e \x01(\x05R\x0eavailableCount\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x10 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x11 \x01(\x03R\tupdatedAt\"\x18\n" +
	"\x16DeleteLeaseProductResp\"I\n" +
	"\x13GetLeaseProductResp\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.leaseproduct.LeaseProductInfoR\x04data\"L\n" +
	"\x16CreateLeaseProductResp\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.leaseproduct.LeaseProductInfoR\x04data\"L\n" +
	"\x16UpdateLeaseProductResp\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.leaseproduct.LeaseProductInfoR\x04data\"6\n" +
	"\x12GetLeaseProductReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\"\x9a\x01\n" +
	"\x14ListLeaseProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\"a\n" +
	"\x15ListLeaseProductsResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.leaseproduct.LeaseProductInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xf1\x02\n" +
	"\x15CreateLeaseProductReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tmachinery\x18\x04 \x01(\tR\tmachinery\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1c\n" +
	"\tdailyRate\x18\a \x01(\x01R\tdailyRate\x12\x18\n" +
	"\adeposit\x18\b \x01(\x01R\adeposit\x12 \n" +
	"\vmaxDuration\x18\t \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\n" +
	" \x01(\x05R\vminDuration\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12&\n" +
	"\x0einventoryCount\x18\f \x01(\x05R\x0einventoryCount\"\xe1\x02\n" +
	"\x15UpdateLeaseProductReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tmachinery\x18\x04 \x01(\tR\tmachinery\x12\x14\n" +
	"\x05brand\x18\x05 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1c\n" +
	"\tdailyRate\x18\a \x01(\x01R\tdailyRate\x12\x18\n" +
	"\adeposit\x18\b \x01(\x01R\adeposit\x12 \n" +
	"\vmaxDuration\x18\t \x01(\x05R\vmaxDuration\x12 \n" +
	"\vminDuration\x18\n" +
	" \x01(\x05R\vminDuration\x12 \n" +
	"\vdescription\x18\v \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\"9\n" +
	"\x15DeleteLeaseProductReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\"\x95\x01\n" +
	"\x1dCheckInventoryAvailabilityReq\x12 \n" +
	"\vproductCode\x18\x01 \x01(\tR\vproductCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\tR\aendDate\"f\n" +
	"\x1eCheckInventoryAvailabilityResp\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12&\n" +
	"\x0eavailableCount\x18\x02 \x01(\x05R\x0eavailableCount2\xe7\x04\n" +
	"\x13LeaseProductService\x12V\n" +
	"\x0fGetLeaseProduct\x12 .leaseproduct.GetLeaseProductReq\x1a!.leaseproduct.GetLeaseProductResp\x12\\\n" +
	"\x11ListLeaseProducts\x12\".leaseproduct.ListLeaseProductsReq\x1a#.leaseproduct.ListLeaseProductsResp\x12_\n" +
	"\x12CreateLeaseProduct\x12#.leaseproduct.CreateLeaseProductReq\x1a$.leaseproduct.CreateLeaseProductResp\x12_\n" +
	"\x12UpdateLeaseProduct\x12#.leaseproduct.UpdateLeaseProductReq\x1a$.leaseproduct.UpdateLeaseProductResp\x12_\n" +
	"\x12DeleteLeaseProduct\x12#.leaseproduct.DeleteLeaseProductReq\x1a$.leaseproduct.DeleteLeaseProductResp\x12w\n" +
	"\x1aCheckInventoryAvailability\x12+.leaseproduct.CheckInventoryAvailabilityReq\x1a,.leaseproduct.CheckInventoryAvailabilityRespB\x10Z\x0e./leaseproductb\x06proto3"

var (
	file_leaseproduct_rpc_proto_rawDescOnce sync.Once
	file_leaseproduct_rpc_proto_rawDescData []byte
)

func file_leaseproduct_rpc_proto_rawDescGZIP() []byte {
	file_leaseproduct_rpc_proto_rawDescOnce.Do(func() {
		file_leaseproduct_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaseproduct_rpc_proto_rawDesc), len(file_leaseproduct_rpc_proto_rawDesc)))
	})
	return file_leaseproduct_rpc_proto_rawDescData
}

var file_leaseproduct_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_leaseproduct_rpc_proto_goTypes = []any{
	(*LeaseProductInfo)(nil),               // 0: leaseproduct.LeaseProductInfo
	(*DeleteLeaseProductResp)(nil),         // 1: leaseproduct.DeleteLeaseProductResp
	(*GetLeaseProductResp)(nil),            // 2: leaseproduct.GetLeaseProductResp
	(*CreateLeaseProductResp)(nil),         // 3: leaseproduct.CreateLeaseProductResp
	(*UpdateLeaseProductResp)(nil),         // 4: leaseproduct.UpdateLeaseProductResp
	(*GetLeaseProductReq)(nil),             // 5: leaseproduct.GetLeaseProductReq
	(*ListLeaseProductsReq)(nil),           // 6: leaseproduct.ListLeaseProductsReq
	(*ListLeaseProductsResp)(nil),          // 7: leaseproduct.ListLeaseProductsResp
	(*CreateLeaseProductReq)(nil),          // 8: leaseproduct.CreateLeaseProductReq
	(*UpdateLeaseProductReq)(nil),          // 9: leaseproduct.UpdateLeaseProductReq
	(*DeleteLeaseProductReq)(nil),          // 10: leaseproduct.DeleteLeaseProductReq
	(*CheckInventoryAvailabilityReq)(nil),  // 11: leaseproduct.CheckInventoryAvailabilityReq
	(*CheckInventoryAvailabilityResp)(nil), // 12: leaseproduct.CheckInventoryAvailabilityResp
}
var file_leaseproduct_rpc_proto_depIdxs = []int32{
	0,  // 0: leaseproduct.GetLeaseProductResp.data:type_name -> leaseproduct.LeaseProductInfo
	0,  // 1: leaseproduct.CreateLeaseProductResp.data:type_name -> leaseproduct.LeaseProductInfo
	0,  // 2: leaseproduct.UpdateLeaseProductResp.data:type_name -> leaseproduct.LeaseProductInfo
	0,  // 3: leaseproduct.ListLeaseProductsResp.list:type_name -> leaseproduct.LeaseProductInfo
	5,  // 4: leaseproduct.LeaseProductService.GetLeaseProduct:input_type -> leaseproduct.GetLeaseProductReq
	6,  // 5: leaseproduct.LeaseProductService.ListLeaseProducts:input_type -> leaseproduct.ListLeaseProductsReq
	8,  // 6: leaseproduct.LeaseProductService.CreateLeaseProduct:input_type -> leaseproduct.CreateLeaseProductReq
	9,  // 7: leaseproduct.LeaseProductService.UpdateLeaseProduct:input_type -> leaseproduct.UpdateLeaseProductReq
	10, // 8: leaseproduct.LeaseProductService.DeleteLeaseProduct:input_type -> leaseproduct.DeleteLeaseProductReq
	11, // 9: leaseproduct.LeaseProductService.CheckInventoryAvailability:input_type -> leaseproduct.CheckInventoryAvailabilityReq
	2,  // 10: leaseproduct.LeaseProductService.GetLeaseProduct:output_type -> leaseproduct.GetLeaseProductResp
	7,  // 11: leaseproduct.LeaseProductService.ListLeaseProducts:output_type -> leaseproduct.ListLeaseProductsResp
	3,  // 12: leaseproduct.LeaseProductService.CreateLeaseProduct:output_type -> leaseproduct.CreateLeaseProductResp
	4,  // 13: leaseproduct.LeaseProductService.UpdateLeaseProduct:output_type -> leaseproduct.UpdateLeaseProductResp
	1,  // 14: leaseproduct.LeaseProductService.DeleteLeaseProduct:output_type -> leaseproduct.DeleteLeaseProductResp
	12, // 15: leaseproduct.LeaseProductService.CheckInventoryAvailability:output_type -> leaseproduct.CheckInventoryAvailabilityResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_leaseproduct_rpc_proto_init() }
func file_leaseproduct_rpc_proto_init() {
	if File_leaseproduct_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaseproduct_rpc_proto_rawDesc), len(file_leaseproduct_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaseproduct_rpc_proto_goTypes,
		DependencyIndexes: file_leaseproduct_rpc_proto_depIdxs,
		MessageInfos:      file_leaseproduct_rpc_proto_msgTypes,
	}.Build()
	File_leaseproduct_rpc_proto = out.File
	file_leaseproduct_rpc_proto_goTypes = nil
	file_leaseproduct_rpc_proto_depIdxs = nil
}
