// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type ApproveLeaseApplicationReq struct {
	ApplicationId    string  `path:"id"`
	Action           string  `json:"action"`
	Suggestions      string  `json:"suggestions"`
	ApprovedDuration int32   `json:"approved_duration"`
	ApprovedAmount   float64 `json:"approved_amount"`
	ApprovedDeposit  float64 `json:"approved_deposit"`
}

type ApproveLeaseApplicationResp struct {
}

type CancelLeaseApplicationReq struct {
	ApplicationId string `path:"id"`
	Reason        string `json:"reason"`
}

type CancelLeaseApplicationResp struct {
}

type CreateLeaseApplicationReq struct {
	ProductId       int64   `json:"product_id"`
	ProductCode     string  `json:"product_code"`
	Name            string  `json:"name"`
	Type            string  `json:"type"`
	Machinery       string  `json:"machinery"`
	StartDate       string  `json:"start_date"`
	EndDate         string  `json:"end_date"`
	Duration        int32   `json:"duration"`
	DailyRate       float64 `json:"daily_rate"`
	TotalAmount     float64 `json:"total_amount"`
	Deposit         float64 `json:"deposit"`
	DeliveryAddress string  `json:"delivery_address"`
	ContactPhone    string  `json:"contact_phone"`
	Purpose         string  `json:"purpose"`
}

type CreateLeaseApplicationResp struct {
	ApplicationId string `json:"application_id"`
}

type GetLeaseApplicationReq struct {
	ApplicationId string `json:"application_id"`
}

type GetLeaseApplicationResp struct {
	ApplicationInfo LeaseApplicationInfo `json:"application_info"`
}

type LeaseApplicationInfo struct {
	Id              int64   `json:"id"`
	ApplicationId   string  `json:"application_id"`
	UserId          int64   `json:"user_id"`
	ApplicantName   string  `json:"applicant_name"`
	ProductId       int64   `json:"product_id"`
	ProductCode     string  `json:"product_code"`
	Name            string  `json:"name"`
	Type            string  `json:"type"`
	Machinery       string  `json:"machinery"`
	StartDate       string  `json:"start_date"`
	EndDate         string  `json:"end_date"`
	Duration        int32   `json:"duration"`
	DailyRate       float64 `json:"daily_rate"`
	TotalAmount     float64 `json:"total_amount"`
	Deposit         float64 `json:"deposit"`
	DeliveryAddress string  `json:"delivery_address"`
	ContactPhone    string  `json:"contact_phone"`
	Purpose         string  `json:"purpose"`
	Status          string  `json:"status"`
	CreatedAt       int64   `json:"created_at"`
	UpdatedAt       int64   `json:"updated_at"`
}

type LeaseApprovalInfo struct {
	Id               int64   `json:"id"`
	ApplicationId    int64   `json:"application_id"`
	AuditorId        int64   `json:"auditor_id"`
	AuditorName      string  `json:"auditor_name"`
	Action           string  `json:"action"`
	Suggestions      string  `json:"suggestions"`
	ApprovedDuration int32   `json:"approved_duration"`
	ApprovedAmount   float64 `json:"approved_amount"`
	ApprovedDeposit  float64 `json:"approved_deposit"`
	CreatedAt        int64   `json:"created_at"`
}

type ListLeaseApplicationsReq struct {
	Page        int32  `form:"page,default=1"`  // 修改为int32统一分页参数
	Size        int32  `form:"size,default=10"` // 修改为int32统一分页参数
	UserId      int64  `form:"user_id,optional"`
	ProductCode string `form:"product_code,optional"`
	Status      string `form:"status,optional"`
}

type ListLeaseApplicationsResp struct {
	List  []LeaseApplicationInfo `json:"list"`
	Total int64                  `json:"total"`
}

type ListLeaseApprovalsReq struct {
	ApplicationId string `form:"application_id"`
}

type ListLeaseApprovalsResp struct {
	List []LeaseApprovalInfo `json:"list"`
}

type UpdateLeaseApplicationReq struct {
	ApplicationId   string `path:"id"`
	Purpose         string `json:"purpose"`
	DeliveryAddress string `json:"delivery_address"`
	ContactPhone    string `json:"contact_phone"`
}

type UpdateLeaseApplicationResp struct {
	ApplicationInfo LeaseApplicationInfo `json:"application_info"`
}
